---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Kafka
  ansible.builtin.systemd:
    name: kafka
    state: restarted
    enabled: yes

- name: Restart ZooKeeper
  ansible.builtin.systemd:
    name: zookeeper
    state: restarted
    enabled: yes
